version: '3.8'

services:
  # Development PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: font_book_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: font_book_management_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/src/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network-dev

  # Adminer for Database Management
  adminer:
    image: adminer:latest
    container_name: font_book_adminer_dev
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - app-network-dev
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
    driver: local

networks:
  app-network-dev:
    driver: bridge